title: Nate Maxwell
description: A blog of various experiments and projects of mine.
url: "https://nate-maxwell.github.io/"

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge
theme: jekyll-theme-hacker
